### ISSUE TITLE
 void redmax::Simmulation::forward(int, bool, bool):Assertion  (q - _q_his[_q_his.size() - 1]).norm() < 1e-7 && (qdot - _qdot_his[_qdot_his.size() - 1]).norm() < 1e-7; failed  已放弃（核心已转储）

### ISSUE THREAD

**Issue by Zlzxzw1234** [yunshengtian/Assemble-Them-All#10]

**Comment by yunshengtian** [comment]
Hello @Zlzxzw1234 let me know if you have specific questions. Thanks

**Comment by taniguchi-t-nmri** [comment]
Sorry for interrupting... 
I also had the same fail, so let me describe it here.

Execution environment: 
- Ubuntu22.04.3 LTS
- conda 23.10.0
- The following commands in "5. test simulation" work correctly.
  """
  python examples/test_joint_sim.py --dir joint_assembly --id 00016 --gravity 9.8 --steps 2000
  100%  |██████████████████████████████████████████| 2000/2000 [01:13<00:00, 27.27it/s]
  Time =  75.90548038482666
  """

When the fail occurs:
- python examples/run_joint_plan.py --planner bfs --dir joint_assembly --id 00016
  """
  python: /home/user/Documents/Assemble-Them-All/simulation/redmax/Simulation.cpp:909: void redmax::Simulation::forward(int, bool, bool):    
  Assertion `(q - _q_his[_q_his.size() - 1]).norm() < 1e-7 && (qdot - _qdot_his[_qdot_his.size() - 1]).norm() < 1e-7' failed.
  Aborted (core dumped)
  """

However, the 00004th in the "joint_assembly" directory is successfully computed.
  """
  python examples/run_joint_plan.py --planner bfs --dir joint_assembly --id 00004
  Status: Success, planning time: 12.665902853012085
  """

(I am very impressed with your work.The follow-up "ASAP" is also excellent.)

**Comment by yunshengtian** [comment]
Thanks @taniguchi-t-nmri for providing more details of the problem!

I tried it on my laptop, and I couldn't reproduce this error. I am using MacBook M1. They were also significantly faster than yours somehow (test_joint_sim.py on 00016 takes 2.83s and run_joint_plan.py on 00016 takes 0.28s).

Let me try later to see if I can reproduce on my linux machine. But anyway, this is a very weird issue that shouldn't happen. I will keep you posted.

**Comment by Zlzxzw1234** [comment]
> Thanks @taniguchi-t-nmri for providing more details of the problem!
> 
> I tried it on my laptop, and I couldn't reproduce this error. I am using MacBook M1. They were also significantly faster than yours somehow (test_joint_sim.py on 00016 takes 2.83s and run_joint_plan.py on 00016 takes 0.28s).
> 
> Let me try later to see if I can reproduce on my linux machine. But anyway, this is a very weird issue that shouldn't happen. I will keep you posted.

May I ask which version ubuntu and anaconda are installed in, and what is the version of conda? My previous code was able to run, but after reinstalling the system, it no longer works. I suspect it's an issue with the anaconda version

**Comment by yunshengtian** [comment]
I tried on my linux machine and still couldn't replicate this issue. I would suggest a simple fix - just comment out the assertion line and rebuild the simulation using `python setup.py install` and see if you can still get something reasonable. Otherwise, we may need to delve deep into the code and check why the assertion has failed.
