### ISSUE TITLE
Setup python issue

### ISSUE THREAD

**Issue by AmazingLc** [yunshengtian/Assemble-Them-All#11]
LINK : warning LNK4044: Unrecognized option '/ldl'; ignored [E:\gitASP\Assemble-Them-All\simulation\build\temp.win-amd64-3.7\Release\redmax\redmax.vcxproj]

**Comment by AmazingLc** [comment]
what is 'ldl' means , i can't find any relevant information about it.How can i fix it?

**Comment by yunshengtian** [comment]
Hi @AmazingLc , I am not very familiar with windows platform. Could you share more information? Maybe the complete output messages.

Also, could you check if you have cloned with `git clone --recurse-submodules`?

**Comment by AmazingLc** [comment]
yes i do it(git clone --recurse-submodules).
More information is:
LINK: warning LNK4044: Unrecognized option "/ldl"; Ignored [E: \ gitASP \ Assemble Them All \ simulation \ build \ temp. win amd64-3.7 \ Release \ redmax \ redmax. vcxproj]
Glfw3. lib (win32_window. obj): error LNK2019: Unresolved external symbol__ IMP_ The symbol [E: \ gitASP \ Assemble Them All \ simulation \ build \ temp. win amd64-3.7 \ Release \ redmax \ redmax. vcxproj] is referenced in the createBitmap function
Glfw3. lib (win32_window. obj): error LNK2019: Unresolved external symbol__ IMP_ DeleteObject, the symbol is referenced in the function createIcon [E: \ gitASP \ Assemble Them All \ simulation \ build \ temp. win amd64-3.7 \ Release \ redmax \ redmax. vcxproj]
E: \ gitASP \ Assemble Them All \ simulation \ build \ temp. win amd64-3.7 \ Release \ redmax \ Release \ redmaxexe: fatal error LNK1120: 16 unresolved external commands [E: \ gitASP \ Assemble Them All \ simulation \ build \ temp. win amd64-3.7 \ Release \ redmax \ redmax. vcxproj]
![微信图片_20240125164309](https://github.com/yunshengtian/Assemble-Them-All/assets/133312066/ff58c803-ef8f-4695-a300-5ea9837dec0f)

**Comment by AmazingLc** [comment]
Yesterday I asked someone who understood better to help me take a look, but after a long time, he still couldn't fix the error message.I don't know how to do now, so I need ask you. I'm really sorry for this little thing.

**Comment by yunshengtian** [comment]
It's ok, no worries. The ldl thing is probably related to [this line](https://github.com/yunshengtian/Assemble-Them-All/blob/395ee5b638ccaa0cbe5b48101655560e49365195/simulation/CMakeLists.txt#L48) in simulation/redmax/CMakeLists.txt, maybe try removing this line when building the simulation?

For the errors from Glfw3.lib, I have little clue so I asked ChatGPT and below is what I got, hope it will be useful:

Solution: Ensure that GLFW is correctly linked in your project, and you're using the correct version of the GLFW library that matches your project's configuration (32-bit vs. 64-bit, debug vs. release).

Verify GLFW Linking: Make sure that GLFW is correctly linked in your project settings. You should have glfw3.lib added to your linker input settings in Visual Studio.

Check Project Configuration: Ensure that your project's platform target matches the GLFW library version you're linking against (e.g., x64 vs. Win32).

Dependencies: If createBitmap is not a GLFW function but rather part of another library or your own code, ensure that this library or the object file containing createBitmap is also linked correctly.

If you're not directly using a function named createBitmap, it might be an indirect dependency, possibly from an extension or an additional library requiring linkage. In such a case, identifying and linking against this missing library is essential.

**Comment by yunshengtian** [comment]
Hi, just want to check in and let me know if there is anything I can help?
