### ISSUE TITLE
XML Modeling Documentation

### ISSUE THREAD

**Issue by sam-dirac** [yunshengtian/Assemble-Them-All#13]
I'm really impressed by this project, but I'm wondering where I can find more information about the XML input to the simulation. Where can I find a description of the different expected XML fields that are supported by the RedMax Simulation object? I can see the code that is parsing the XML data, but I would love some reference material if it is available. How did you know what to put in the XML files that you in your examples?

**Comment by yunshengtian** [comment]
Hi @sam-dirac , there is no direct reference material available for our XML, but the XML is similar to a URDF structure that is hopefully straightforward to interpret - there are sections for setting up general/default simulation configs, robot kinematic structures, contacts, and actuators.  

You can find more XML examples in this github repo: https://github.com/eanswer/DiffHand/tree/master/assets

For simulation there is a note in REDMAX's original github repo for the theoretical foundation of the simulation, if this is helpful: https://github.com/sueda/redmax

**Comment by sam-dirac** [comment]
Okay, thank you! I really appreciate all of your work on this repo

**Comment by yunshengtian** [comment]
You're welcome!
