### ISSUE TITLE
May I ask if this algorithm only supports the OBJ format? Or does it also support step format and so on?

### ISSUE THREAD

**Issue by Zlzxzw1234** [yunshengtian/Assemble-Them-All#15]

**Comment by yunshengtian** [comment]
Technically, the algorithm does not depend on the file format of the mesh.
However, the current code only supports OBJ. For [example](https://github.com/yunshengtian/Assemble-Them-All/blob/395ee5b638ccaa0cbe5b48101655560e49365195/simulation/redmax/Body/BodyMeshObj.cpp#L51). 
I assume converting from STEP or other formats to OBJ should be straightforward, but it is also possible to rewrite the APIs for loading and processing meshes in our code.
