### ISSUE TITLE
I would like to ask if this code can be run in a Windows environment？

### ISSUE THREAD

**Issue by Zlzxzw1234** [yunshengtian/Assemble-Them-All#18]

**Comment by yunshengtian** [comment]
It should be, but I have not tested it. The simulation compilation may need some custom steps, and I am not sure if all dependencies run smoothly on Windows.

**Comment by Interrollipsis** [comment]
I'm glad this thread was made because I had the same question. 

> It should be, but I have not tested it. The simulation compilation may need some custom steps, and I am not sure if all dependencies run smoothly on Windows.

exactly what environment was it created in?

**Comment by Interrollipsis** [comment]
I'll try to get it working in windows but the redmax_py library doesn't seem to be building.

**Comment by yunshengtian** [comment]
This is from my labmate who tried to build on windows and made it work. Let me know if this helps.

"When running `python setup.py install`, you might encounter some compile errors with M_PI being undefined or something like that. To fix it, add #define _USE_MATH_DEFINES to the top of simulation/redmax/CollisionDetection/ode/odeBoxBox.cpp. In addition, comment out the line set(CMAKE_CXX_STANDARD_LIBRARIES -ldl)  in both simulation/CMakeLists.txt and simulation/redmax/CMakeLists.txt , since this library doesn't exist on Windows."

And use this environment yml instead: https://drive.google.com/file/d/1FZm8f-d3ba09MEEIJ1fQkRw7fnKZStaw/view?usp=sharing

**Comment by kalieching** [comment]
Hi! I am trying to set up in a windows environment. setup.py seems to hang for a while (10+ min) when I am at the part where it outputs:
```
ForceGeneralPrimitiveContact.cpp
C:[path]\Assemble-Them-All\simulation\redmax\Utils.h(340,1): warning C4267: 'argument': conversion from 'size_t' to 'int', possi
          ]
C:[path]\Assemble-Them-All\simulation\redmax\Utils.h(340,56):          ]
C:[path]\Assemble-Them-          ]
C:[path]\Assemble-Them-All\simulation\redmax\Utils.h(340,56): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Deriv
ed>::Index' to 'int', possible loss of data [C:[path]\Assemble-Them-All\simulation\build\temp.win-amd64-cpython-311\Release\redm
ax\redmax.vcxproj]
          with
          [
              Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>   
          ]
  Generating Code...
```

Is this any cause for concern? How much time should I allow it? tyia!

**Comment by FloatFrank** [comment]
> This is from my labmate who tried to build on windows and made it work. Let me know if this helps.
> 
> "When running `python setup.py install`, you might encounter some compile errors with M_PI being undefined or something like that. To fix it, add #define _USE_MATH_DEFINES to the top of simulation/redmax/CollisionDetection/ode/odeBoxBox.cpp. In addition, comment out the line set(CMAKE_CXX_STANDARD_LIBRARIES -ldl) in both simulation/CMakeLists.txt and simulation/redmax/CMakeLists.txt , since this library doesn't exist on Windows."
> 
> And use this environment yml instead: https://drive.google.com/file/d/1FZm8f-d3ba09MEEIJ1fQkRw7fnKZStaw/view?usp=sharing

Windows11, same with this method but Error message, can you help me? Thank you!: 
sdfgen.lib(makelevelset3.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(Act
uator.obj 中) [E:\Assemble-Them-All\Assemble-Them-All\simulation\build\temp.win-amd64-3.7\Release\redmax\redmax.vcx
proj]
LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library [E:\Assemble-Them-All\Assemble-Them-All\sim
ulation\build\temp.win-amd64-3.7\Release\redmax\redmax.vcxproj]
E:\Assemble-Them-All\Assemble-Them-All\simulation\build\temp.win-amd64-3.7\Release\redmax\Release\redmax.exe : fat
al error LNK1319: 检测到 1 个不匹配项 [E:\Assemble-Them-All\Assemble-Them-All\simulation\build\temp.win-amd64-3.7\Release\
redmax\redmax.vcxproj]
