### ISSUE TITLE
Not able to setup in windows 11

### ISSUE THREAD

**Issue by JeevananthamSathish** [yunshengtian/Assemble-Them-All#21]
[ERROR.txt](https://github.com/user-attachments/files/17706874/ERROR.txt)

- I am trying to install this setup in windows 11 but getting some error which i couldn't figure it out
- I have attached the error here.
- I have made the changes which you have mentioned for windows 10 but still getting the error

**Comment by yunshengtian** [comment]
Hi, I think you need to clone the repo with the `--recurse-submodules` flag. Let me know if it works

**Comment by JeevananthamSathish** [comment]
Thanks, Installed it . running without any error. Thanks for your quick response.

**Comment by JeevananthamSathish** [comment]
Issue is resolved
