### ISSUE TITLE
SimRenderer gives me black images

### ISSUE THREAD

**Issue by ttsesm** [yunshengtian/Assemble-Them-All#5]
Hi @yunshengtian, 

I am trying to render the states output by setting the `--render` and the `--record-dir` parameters but the output is a black .gif file. With a quick debugging I've noticed that the output from the the `sim.replay()` [here](https://github.com/yunshengtian/Assemble-Them-All/blob/a77aa7313184a49ccb7b40ac34ecb3fd96e297c6/utils/renderer.py#L19) is back images:
![image](https://user-images.githubusercontent.com/10189018/222475767-cd8f4f5e-da9d-4805-934c-a3225b71e5fa.png)
I am not sure though what could be causing this, any idea?

**Comment by yunshengtian** [comment]
This is a great catch. Thank you for bringing this up. Could you try commenting out [this line](https://github.com/yunshengtian/Assemble-Them-All/blob/a77aa7313184a49ccb7b40ac34ecb3fd96e297c6/simulation/opengl_viewer/src/viewer.cpp#L159)? I remember on macos and linux I need different settings on this.

**Comment by ttsesm** [comment]
> This is a great catch. Thank you for bringing this up. Could you try commenting out [this line](https://github.com/yunshengtian/Assemble-Them-All/blob/a77aa7313184a49ccb7b40ac34ecb3fd96e297c6/simulation/opengl_viewer/src/viewer.cpp#L159)? I remember on macos and linux I need different settings on this.

Sure, I forgot to mention my system which is linux. Btw, after commenting that line I will have to rerun the `python setup.py install`  right?

**Comment by yunshengtian** [comment]
Yes. How that goes?

**Comment by ttsesm** [comment]
Yes, this works now ;-)

![06397](https://user-images.githubusercontent.com/10189018/222691171-07fcb406-4352-45a9-b5b8-ace84e6c8c4a.gif)
