### ISSUE TITLE
what does output mean --save-dir? 

### ISSUE THREAD

**Issue by IDONTSUDO** [yunshengtian/Assemble-Them-All#6]
Hello, thank you very much for the work you have done. I'm trying to integrate your toolpath solution into my automated assembly project. The --save-dir argument generates a set of arrays with a length of 100 nested arrays on my test build. In the example, I reduced it to three nested arrays. Could you explain what the numbers in these arrays mean?

This is the output of the t_plan variable from https://github.com/yunshengtian/Assemble-Them-All/blob/main/baselines/run_joint_plan.py#LL310C21-L310C25

```
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  2.64617134e-32]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -3.78024540e-32]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.53810015e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  4.52211259e-32]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -6.46016192e-32]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  2.62850025e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  4.66938017e-32]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -6.67054421e-32]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  2.71410026e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
 ```

**Comment by yunshengtian** [comment]
Hi @IDONTSUDO , I think this is the output from `path` instead of `t_plan`. `path` is a list of states that correspond to a motion trajectory for disassembly, and `t_plan` is the total time spent on planning.

**Comment by yunshengtian** [comment]
To be more clear, each state in the `path` is defined as a 4x4 transformation matrix on the moving part.

**Comment by IDONTSUDO** [comment]
@yunshengtian  thx!
