### ISSUE TITLE
failed running the test_joint_sim.py | throws error [ERROR] Body type error : SDF

### ISSUE THREAD

**Issue by aiswaryame94** [yunshengtian/Assemble-Them-All#7]
I ran : python examples/test_joint_sim.py --dir joint_assembly_dense --id 00016 --gravity 9.8 --steps 2000
Error: 
[Error] Body type error: SDF
Traceback (most recent call last):
  File "examples/test_joint_sim.py", line 103, in <module>
    sim = redmax.Simulation(xml_file_path)
RuntimeError: Caught an unknown exception!

Changed the type to MESH and CUBOIDS as well. Did not work. Kindly provide help regarding the same. I am unable to load the xml file that creates /uses sdf objects.

**Comment by yunshengtian** [comment]
I couldn't replicate this error. The command runs fine on my end. Maybe rebuilding the simulation could help but hope this issue was resolved as I see it's closed now.
