### ISSUE TITLE
/subdivide_batch.py // edge_length_dict // dose not exist

### ISSUE THREAD

**Issue by Ludwig-Karl** [yunshengtian/Assemble-Them-All#8]
Hello, thank you very much for the work you have done. Can you help me with subdeviding the meshes. 

for all processes I get this:

Process Process-6:                                                                                                      Traceback (most recent call last):                                                                                        File "/opt/conda/envs/assembly/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                         self.run()                                                                                                            File "/opt/conda/envs/assembly/lib/python3.7/multiprocessing/process.py", line 99, in run                                 self._target(*self._args, **self._kwargs)                                                                             File "/mnt/Assemble-Them-All/utils/parallel.py", line 6, in parallel_worker                                               result = worker(*args)                                                                                                File "/mnt/Assemble-Them-All/assets/subdivide.py", line 98, in subdivide_assembly                                         new_mesh = subdivide_to_size(mesh, max_edge)                                                                          File "/mnt/Assemble-Them-All/assets/subdivide.py", line 34, in subdivide_to_size                                          longest_edge_length = edge_length_dict[longest_edge]                                                                KeyError: (12338, 12300)

**Comment by yunshengtian** [comment]
Hi @Ludwig-Karl ,

This error is because the dependency library `sortedcontainers` in subdivide.py seems to have issues on different platforms. I will later post a shared link to the subdivided meshes.

**Comment by yunshengtian** [comment]
Link to subdivided two-part dataset: https://drive.google.com/uc?id=1Ws3Cduh81iCqvVZ3pRskUIhDgZvgOyu0
Link to subdivided multi-part dataset: https://drive.google.com/uc?id=1dQRH5K4GCd1HebkWqHd4LuazWaIvEdtA

**Comment by yunshengtian** [comment]
I'll close it if there is no further issues
